# Site settings
title:       国学之旅
email:       irisjiangwhu@gmail.com 
author:      Iris Jiang
description: "为爱好国学的小伙伴提供阅读、学习平台"
baseurl:     ""
url:         "https://iris-jiang.github.io/learnguoxue/"

#Duoshuo short Name / 多说的shortname
# duoshuo: iris_whu
disqus_shortname: https-iris-jiang-github-io-learnguoxue
#Baidu analytics / 百度统计(异步的js码，注意使用异步版本的)
baidu_analyze: 

# Google analytics
google_analytics: UA-89578578-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Plugins:
gems:      [jekyll-paginate]


# Build settings
markdown:     kramdown
paginate:     5
sass:
  compressed: true

